import type { Metadata } from 'next';

import { Playground } from '@/components/playground/playground';
import { site } from '@/components/site-config';

export const metadata: Metadata = {
  title: 'Playground',
  description: `Paste an OpenAPI or Swagger schema, tweak the options and download the TypeScript client generated by ${site.name}.`,
  openGraph: { title: `Playground · ${site.name}` },
};

export default function PlaygroundPage() {
  return (
    <main id="main" className="min-w-0">
      <Playground />
    </main>
  );
}
